name: simple_date_time
description: A lightweight Flutter utility to format date and time safely with presets.
version: 0.0.1
repository: https://github.com/pankaj101/simple_date_time
issue_tracker: https://github.com/pankaj1101/simple_date_time/issues
homepage: https://pub.dev/packages/simple_date_time

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
